entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada
app_name = 'entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name='list_entrada'),
    path('new_entrada/', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada'),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida')),
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto
app_name = 'produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto'),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida
app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida, name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name='delete_saida'),
]

entrada/models.py
from django.db import models
from produto.models import Produtos, Cores
class Entradas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name="Produto")
    
    preco = models.DecimalField("Preço", decimal_places=2, max_digits=8, default=0)
    
    quantidade = models.IntegerField("Quantidade", default=0)

    criado = models.DateTimeField("Criado em", auto_now_add=True)
    
    modificado = models.DateTimeField("Modificado em", auto_now=True)

    def __str__(self) -> str:
        return self.produto.produto

    class Meta:
        verbose_name = 'Entrada'
        verbose_name_plural = 'Entradas'
        ordering = ['produto'] 
    

entrada/forms.py
from django.forms import ModelForm, TextInput, Select
from .models import Entradas
class EntradaForm(ModelForm):
    class Meta:
        model = Entradas
        fields = ['produto', 'quantidade', 'preco']

entrada/views.py
from django.shortcuts import render, redirect
from .models import Entradas
from .forms import EntradaForm

def list_entrada(request):
    entradas = Entradas.objects.all()
    template_name = 'list_entrada.html'
    context = {
        'entradas': entradas,
    }
    return render(request, template_name, context)

def new_entrada(request):
    if request.method == 'POST':
        form = EntradaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    else:
        template_name = 'new_entrada.html'
        context = {
        'form': EntradaForm(),
        }
        return render(request, template_name, context)
        
def update_entrada(request, pk):
    entrada = Entradas.objects.get(id=pk)
    quantidade_nota_antiga = entrada.quantidade
    if request.method == 'POST':
        form = EntradaForm(request.POST, instance=entrada)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - quantidade_nota_antiga + form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('entrada:list_entrada')
    else:
        template_name = 'update_entrada.html'
        context = {
        'form': EntradaForm(instance=entrada),
        'pk': pk,
        }
        return render(request, template_name, context)
    
def delete_entrada(request, pk):
    entrada = Entradas.objects.get(id=pk)
    quantidade_nota_antiga = entrada.quantidade
    entrada.produto.quantidade = entrada.produto.quantidade - quantidade_nota_antiga
    entrada.produto.save()
    entrada.delete()
    return redirect('entrada:list_entrada')

entrada/templates/list_entrada.html
{% extends 'base.html' %}

{% block product %}
<p>
    <a class="button is-warning" href="{% url 'index' %}"><b>Início</b></a>
    <a class="button is-warning" href="{% url 'produto:list_produto' %}"><b>Lista de Produtos</b></a> 
    <a class="button is-warning" href="{% url 'saida:list_saida' %}"><b>Lista de Saidas</b></a> <br><br>
    <h1>Entrada</h1> 
    <a class="button is-warning" href="{% url 'entrada:new_entrada' %}"><b>Novo</b></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Cor</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for entrada in entradas %}
        <tr>
            <td>{{ entrada.id }}</td>
            <td>{{ entrada.produto }}</td>
            <td>{{ entrada.produto.cor }}</td>
            <td>{{ entrada.preco }}</td>
            <td>{{ entrada.quantidade }}</td>
            <td><a class="button is-warning" href="{% url 'entrada:update_entrada' entrada.id %}"><b>alterar</b></a></td>
            <td><a class="button is-warning" href="{% url 'entrada:delete_entrada' entrada.id %}"><b>deletar</b></a></td>       
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

entrada/templates/new_entrada.html
{% extends 'base.html' %}

{% block product %}
<h1>Entrada</h1>

<form action="{% url 'entrada:new_entrada' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
        <label class="label">{{ field.label }}</label>
        <div class="control">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <button class="button is-warning" type="submit"><b>Salvar</b></button>
</form>


{% endblock %}

entrada/templates/update_entrada.html
{% extends 'base.html' %}

{% block product %}
<h1>Entrada update</h1>

<form action="{% url 'entrada:update_entrada' pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-warning" type="submit"><b>Salvar</b></button>
</form>
{% endblock %}