entrada/urls.py
from django.urls import path
from .views import list_entrada, new_entrada, update_entrada, delete_entrada
app_name = 'entrada'
urlpatterns = [
    path('list_entrada/', list_entrada, name='list_entrada'),
    path('new_entrada/', new_entrada, name='new_entrada'),
    path('update_entrada/<int:pk>/', update_entrada, name='update_entrada'),
    path('delete_entrada/<int:pk>/', delete_entrada, name='delete_entrada'),
]

estoque/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', index, name = 'index'),
    path('admin/', admin.site.urls),
    path('produto/', include('produto.urls', namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')),
    path('saida/', include('saida.urls', namespace='saida')),
]

produto/urls.py
from django.urls import path
from .views import list_produto, new_produto, update_produto, delete_produto
app_name = 'produto'
urlpatterns = [
    path('list_produto/', list_produto, name='list_produto'),
    path('new_produto/', new_produto, name='new_produto'),
    path('update_produto/<int:pk>/', update_produto, name='update_produto'),
    path('delete_produto/<int:pk>/', delete_produto, name='delete_produto'),
]

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida
app_name = 'saida'
urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida, name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida, name='delete_saida'),
]

saida/models.py
from django.db import models
from produto.models import Produtos
class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name="Produto")

    quantidade = models.IntegerField("Quantidade", default=0)

    preco = models.DecimalField("Preço", decimal_places=2, max_digits=8, default=0)

    retirado = models.DateTimeField("Retirado em", auto_now_add=True)
    
    modificado = models.DateTimeField("Modificado em", auto_now=True)

    def __str__(self) -> str:
        return self.produto.produto

    class Meta:
        verbose_name = 'Saida'
        verbose_name_plural = 'Saidas'
        ordering = ['produto']

saida/forms.py
from django.forms import ModelForm, TextInput, Select
from .models import Saidas
class SaidaForm(ModelForm):
    class Meta:
        model = Saidas
        fields = ['produto', 'quantidade']

saida/views.py
from django.shortcuts import render, redirect
from .models import Saidas
from .forms import SaidaForm

def list_saida(request):
    saidas = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
        'saidas': saidas, 
    }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'new_saida.html'
        context = {
        'form': SaidaForm(),
        }
        return render(request, template_name, context)
        
def update_saida(request, pk):
    saida = Saidas.objects.get(id=pk)
    quantidade_nota_antiga = saida.quantidade
    if request.method == 'POST':
        form = SaidaForm(request.POST, instance=saida)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade + quantidade_nota_antiga - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    else:
        template_name = 'update_saida.html'
        context = {
        'form': SaidaForm(instance=saida),
        'pk': pk,
        }
        return render(request, template_name, context)
    
def delete_saida(request, pk):
    saida = Saidas.objects.get(id=pk)
    quantidade_nota_antiga = saida.quantidade
    saida.produto.quantidade = saida.produto.quantidade + quantidade_nota_antiga
    saida.produto.save()
    saida.delete()
    return redirect('saida:list_saida')

saida/templates/list_saida.html
{% extends 'base.html' %}

{% block product %}
<p>
    <a class="button is-warning" href="{% url 'index' %}"><b>Início</b></a>
    <a class="button is-warning" href="{% url 'produto:list_produto' %}"><b>Lista de Produtos</b></a> 
    <a class="button is-warning" href="{% url 'entrada:list_entrada' %}"><b>Lista de Entradas</b></a> <br><br>
    <h1>Saída</h1> 
    <a class="button is-warning" href="{% url 'saida:new_saida' %}"><b>Novo</b></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for saida in saidas %}
        <tr>
            <th>{{ saida.id }}</th>
            <td>{{ saida.produto }}</td>
            <td>{{ saida.produto.preco }}</td>
            <td>{{ saida.quantidade }}</td>
            <td><a class="button is-warning" href="{% url 'saida:update_saida' saida.id %}"><b>alterar</b></a></td>
            <td><a class="button is-warning" href="{% url 'saida:delete_saida' saida.id %}"><b>deletar</b></a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

saida/templates/new_saida.html
{% extends 'base.html' %}

{% block product %}
<h1>Saída</h1>

<form action="{% url 'saida:new_saida' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="field">
        <label class="label">{{ field.label }}</label>
        <div class="control">
            {{ field }}
        </div>
    </div>
    {% endfor %}
    <button class="button is-warning" type="submit"><b>Salvar</b></button>
</form>


{% endblock %}

saida/templates/update_saida.html
{% extends 'base.html' %}

{% block product %}
<h1>Saída update</h1>

<form action="{% url 'saida:update_saida' pk %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-warning" type="submit"><b>Salvar</b></button>
</form>
{% endblock %}